@MicroRabbit.Banking.Api_HostAddress = http://localhost:5260

POST {{MicroRabbit.Banking.Api_HostAddress}}/api/Banking
Content-Type: application/json

{
  "accountFrom": 10001,
  "accountTo": 2001,
  "transferAmount": 10000
}

###
